version: 2

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - main: .
    binary: sma_chg_log
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

dockers_v2:
  - images:
      - "ghcr.io/joshiste/sma_chg_log"
    tags:
      - "{{ .Tag }}"
      - latest
    labels:
      "org.opencontainers.image.description": "SMA EV Charging Log"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

release:
  github:
    owner: joshiste
    name: sma_chg_log
  mode: append
  header: |
    ## SMA EV Charging Log {{ .Tag }}
  extra_files:
    - glob: ./LICENSE
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refa:"
